# Generated by Django 5.2.3 on 2025-06-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='zentorauser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
